export const endpoints = {
    user: 'spotify/me',
    userTopTracks: 'spotify/topTracks',
    userTopArtists: 'spotify/topArtists',
    userPlayer: 'spotify/player',
    currentlyPlaying: 'spotify/player/currently-playing',
    startStopPlaying: 'spotify/player/play',
    userFollowedArtists: 'spotify/followedArtists',
    newReleases: 'spotify/newReleases',
    userShows: 'spotify/shows',
    showEpisode: '/spotify/shows/',
    userPlaylists: 'spotify/playlists',
    playlist: '/spotify/playlist/',
    userAlbums: 'spotify/albums',
    checkSavedEpisodes: '/spotify/checkSavedEpisode/',
}
